# -*- coding: utf-8 -*-
"""connect4AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iglbKHxjlFkjes5N1FEiECTgutHALbgI
"""

import math
import random

ROWS = 6
COLS = 7
MAX_DEPTH = 10   # safe depth for Python

class BitBoard:
    def __init__(self):
        self.mask = 0
        self.position = 0
        self.moves = []

    def copy(self):
        b = BitBoard()
        b.mask = self.mask
        b.position = self.position
        b.moves = self.moves.copy()
        return b

    def can_play(self, col):
        return (self.mask & (1 << (col*7 + 5))) == 0

    def possible_moves(self):
        return [c for c in range(COLS) if self.can_play(c)]

    def play(self, col):
        self.position ^= self.mask
        self.mask |= self.mask + (1 << (col*7))
        self.moves.append(col)

    def is_win_for(self, pos):
        m = pos & (pos >> 1)
        if m & (m >> 2): return True

        m = pos & (pos >> 7)
        if m & (m >> 14): return True

        m = pos & (pos >> 6)
        if m & (m >> 12): return True

        m = pos & (pos >> 8)
        if m & (m >> 16): return True

        return False

    def is_win(self):
        return self.is_win_for(self.position ^ self.mask)

    def is_winning_move(self, col):
        temp = self.copy()
        temp.play(col)
        return temp.is_win()


# ================= NEGAMAX =================

transposition = {}

def negamax(board, depth, alpha, beta):
    key = (board.mask, board.position)
    if key in transposition:
        return transposition[key]

    if board.is_win():
        return -1000 + len(board.moves)

    if depth == 0 or len(board.moves) == ROWS*COLS:
        return 0

    max_score = -math.inf

    for col in sorted(board.possible_moves(), key=lambda c: abs(c-3)):
        if board.is_winning_move(col):
            return 1000 - len(board.moves)

        child = board.copy()
        child.play(col)

        score = -negamax(child, depth-1, -beta, -alpha)

        max_score = max(max_score, score)
        alpha = max(alpha, score)

        if alpha >= beta:
            break

    transposition[key] = max_score
    return max_score


def ai_move(board):
    best_score = -math.inf
    best_col = random.choice(board.possible_moves())

    for col in sorted(board.possible_moves(), key=lambda c: abs(c-3)):
        if board.is_winning_move(col):
            return col

        child = board.copy()
        child.play(col)

        score = -negamax(child, MAX_DEPTH, -math.inf, math.inf)

        if score > best_score:
            best_score = score
            best_col = col

    return best_col


# ================= PRINT =================

def print_board(board):
    grid = [["." for _ in range(COLS)] for _ in range(ROWS)]

    player = 1  # X starts
    heights = [0]*COLS

    for col in board.moves:
        row = heights[col]
        grid[row][col] = "X" if player == 1 else "O"
        heights[col] += 1
        player *= -1

    print("\n  1 2 3 4 5 6 7")
    for r in reversed(range(ROWS)):
        print(r+1, " ".join(grid[r]))
    print()


# ================= GAME MODES =================

def human_vs_ai(play_first=True):
    board = BitBoard()
    if play_first:
      print("You are X")
    else:
      print("You are O")
    print_board(board)

    while True:
        # Human goes first if play_first=True
        if play_first:
            if len(board.moves) == ROWS * COLS:
                print("Draw!")
                break
            # Human move
            while True:
                try:
                    col = int(input("Choose column (1-7): ")) - 1
                    if 0 <= col < COLS and board.can_play(col):
                        break
                    print("Invalid.")
                except:
                    print("Enter 1-7.")

            board.play(col)
            print_board(board)

            if board.is_win():
                print("You win!")
                break

            # AI move
            col = ai_move(board)
            print(f"AI plays column {col+1}")
            board.play(col)
            print_board(board)

            if board.is_win():
                print("AI wins!")
                break
        else:
            if len(board.moves) == ROWS * COLS:
                print("Draw!")
                break
            # AI goes first
            col = ai_move(board)
            print(f"AI plays column {col+1}")
            board.play(col)
            print_board(board)

            if board.is_win():
                print("AI wins!")
                break

            

            # Human move
            while True:
                try:
                    col = int(input("Choose column (1-7): ")) - 1
                    if 0 <= col < COLS and board.can_play(col):
                        break
                    print("Invalid.")
                except:
                    print("Enter 1-7.")

            board.play(col)
            print_board(board)

            if board.is_win():
                print("You win!")
                break



def ai_vs_ai():
    board = BitBoard()
    print_board(board)

    while True:
        col = ai_move(board)
        board.play(col)
        print(f"Move {len(board.moves)}: {col+1}")
        print_board(board)

        if board.is_win():
            print("Game over")
            break
        if len(board.moves) == ROWS * COLS:
          print("Draw!")
          break


if __name__ == "__main__":
    print("1: Human vs AI")
    print("2: AI vs AI")
    
    while True:
      mode = input("Choose: ")
      if mode == "1":
        while True:
          play_first = input("Do you want to play first? (y/n): ")
          if play_first == "y":
            human_vs_ai(True)
            break
          if play_first == "n":
            human_vs_ai(False)
            break
        print("\n")
        break
          
      if mode == "2":
          ai_vs_ai()
          break
